/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const DEBOUNCE_DELAY: typeof import('./scripts/features/Sidebar/config/constants').DEBOUNCE_DELAY
  const EMPTY_STATE_HEIGHT: typeof import('./scripts/features/Sidebar/config/constants').EMPTY_STATE_HEIGHT
  const Fragment: typeof import('react').Fragment
  const HIGHLIGHT_DELAY: typeof import('./scripts/features/Sidebar/config/constants').HIGHLIGHT_DELAY
  const LOADING_CENTER_HEIGHT: typeof import('./scripts/features/Sidebar/config/constants').LOADING_CENTER_HEIGHT
  const SELECTION_REMOVE_DELAY: typeof import('./scripts/features/Sidebar/config/constants').SELECTION_REMOVE_DELAY
  const SIDEBAR_DEFAULT_WIDTH: typeof import('./scripts/features/Sidebar/config/constants').SIDEBAR_DEFAULT_WIDTH
  const SIDEBAR_MAX_WIDTH: typeof import('./scripts/features/Sidebar/config/constants').SIDEBAR_MAX_WIDTH
  const SIDEBAR_MIN_WIDTH: typeof import('./scripts/features/Sidebar/config/constants').SIDEBAR_MIN_WIDTH
  const SIDEBAR_RESIZE_HANDLE_WIDTH: typeof import('./scripts/features/Sidebar/config/constants').SIDEBAR_RESIZE_HANDLE_WIDTH
  const SIDEBAR_Z_INDEX: typeof import('./scripts/features/Sidebar/config/constants').SIDEBAR_Z_INDEX
  const Suspense: typeof import('react').Suspense
  const TRANSITION_CLEANUP_DELAY: typeof import('./scripts/features/Sidebar/config/constants').TRANSITION_CLEANUP_DELAY
  const TREE_BASE_INDENT: typeof import('./scripts/features/Sidebar/config/constants').TREE_BASE_INDENT
  const TREE_CHEVRON_SIZE: typeof import('./scripts/features/Sidebar/config/constants').TREE_CHEVRON_SIZE
  const TREE_ICON_SIZE: typeof import('./scripts/features/Sidebar/config/constants').TREE_ICON_SIZE
  const TREE_INDENT_PER_LEVEL: typeof import('./scripts/features/Sidebar/config/constants').TREE_INDENT_PER_LEVEL
  const TREE_SPACER_WIDTH: typeof import('./scripts/features/Sidebar/config/constants').TREE_SPACER_WIDTH
  const URL_POLLING_INTERVAL: typeof import('./scripts/features/Sidebar/config/constants').URL_POLLING_INTERVAL
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useMemo: typeof import('react').useMemo
  const useOptimistic: typeof import('react').useOptimistic
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
  const useTranslation: typeof import('react-i18next').useTranslation
}
